// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChA5zaG7tUE1YXEHUl2Ur0BLRvkhDpYsw',
    appId: '1:414392371330:web:ee1a9a2416989bc9d44c9b',
    messagingSenderId: '414392371330',
    projectId: 'food-e-82b20',
    authDomain: 'food-e-82b20.firebaseapp.com',
    storageBucket: 'food-e-82b20.firebasestorage.app',
    measurementId: 'G-Z0KMFHDJ9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UnAu1SqxVPvktExw24B5QNFgI_5mq8U',
    appId: '1:414392371330:android:962dd10ddd20b69bd44c9b',
    messagingSenderId: '414392371330',
    projectId: 'food-e-82b20',
    storageBucket: 'food-e-82b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGCLCeqdgkMHusPLo_QFAE4PHcMwqoEo',
    appId: '1:414392371330:ios:f50ad5f6ede0f5a5d44c9b',
    messagingSenderId: '414392371330',
    projectId: 'food-e-82b20',
    storageBucket: 'food-e-82b20.firebasestorage.app',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGCLCeqdgkMHusPLo_QFAE4PHcMwqoEo',
    appId: '1:414392371330:ios:f50ad5f6ede0f5a5d44c9b',
    messagingSenderId: '414392371330',
    projectId: 'food-e-82b20',
    storageBucket: 'food-e-82b20.firebasestorage.app',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChA5zaG7tUE1YXEHUl2Ur0BLRvkhDpYsw',
    appId: '1:414392371330:web:38f8d9291ce193c5d44c9b',
    messagingSenderId: '414392371330',
    projectId: 'food-e-82b20',
    authDomain: 'food-e-82b20.firebaseapp.com',
    storageBucket: 'food-e-82b20.firebasestorage.app',
    measurementId: 'G-Z9WL0ERKGY',
  );
}
